### ISSUE TITLE
Flysky fs-i6 transmitter not mapping correctly 

### ISSUE THREAD

**Issue by skellator** [CurryKitten/CurryKitten-Sim#17]
Hello,
I am experiencing an issue with the mapping of the flysky fs-i6 mapping. It is only allowing the throttle to center stick and back. Roll will only roll to the left and I have no Yaw and minimal pitch.

**Comment by howels** [comment]
Can you see the axis working correctly in a joystick testing app? Sounds like your axis are only transmitting positive values and not negative ones.  Try finding something that shows the joystick positions in your OS and updating the mappings on the radio so that it sends the full range for each axis. Cos I think this app is simply taking whatever the first four joystick axis are and using those.

**Comment by CurryKitten** [comment]
I've opened up a more general issue to tackle issues with controllers in #20 so closing this issue to avoid duplication
