### ISSUE TITLE
Add preset rates for beginner/intermediate/advanced pilots on gamepad and radio types

### ISSUE THREAD

**Issue by DroneFletch** [CurryKitten/CurryKitten-Sim#22]
Ability to change gamepad sensitivity.

**Comment by CurryKitten** [comment]
Can you expand on this a bit please.  Gamepads feel very sensitive because the stick travel is very short.  What you can do is adjust some of the rates to help you.  I mentioned in the last update video about setting SuperRate to 0.3, RC Expo to 0.4 and RC Rate to 0.5 to help you (also in the wiki from this github repo).

If you are unfamiliar with what these figures do (and I've yet to attempt to explain them as yet) the RC rate is the amount of input vs the stick movement.  1.0 is full stick movement, 0.5 is the full stick movement only giving 50% of it's potential (and thus having more sensitivity within that 50%)

RX Expo is a way of resensitizing the sensitivity in the centre of the stick where you tend to need finer controls, so the higher it is the less sensitive the stick becomes.

Superrate is more complex to explain easily as it described a curve which is based on a mix of rate and expo - but basically the higher it is then the more response you have at the end of the stick.

If these are altered to suit the stick sensitivity will drop right off - but please comment further if you are talking about something different.

**Comment by DroneFletch** [comment]
ah ok. And yes that's what I mean.

**Comment by CurryKitten** [comment]
Ok - please mess around with those values for now, and what I'll do is amend this issue to add some preset rates so for either a gamepad or a radio you'd have the option of clicking on beginner/intermediate/advanced where the idea of beginner is that you can slam the sticks back and forth with the quad moving quite gently - whereas the advanced setup would roll 3 times in 1 second with a full stick

**Comment by DroneFletch** [comment]
Yes makes sense here for this beginner... haha

**Comment by CurryKitten** [comment]
This has now been implemented by pressing "A" on the main game screen for Flight assist.  This will bring up a menu with a bunch of options -

![Screenshot 2020-03-06 at 11 24 31](https://user-images.githubusercontent.com/12443664/76079739-3d3af680-5f9d-11ea-83ea-6c804bc2a4bf.jpg)

I decided to include a power aspect to these options as well as it makes quite a difference when flying - especially when starting out.  I've got it so that the Low power will hover around 50%, medium at around 35% and high at 20%.  The high power, although it's what people asked for is crazy high if you look at a LOS punch out.

The rest of the figures I've manipulated the various rates to get what I think are reasonable values.  I used my regular (and the default start) values for the expert pilot option, and it was easy to set beginner rates - I brought them down until I could slam the stick around without crashing.

Setting intermediate was a bit tricker - I was aiming to be able to move the sticks about midway into regular coordinated turns - we needed a reasonable roll/flip at the stick extents, but not too fast.  Of course, people to turn from these as base rates if they like.

One thing that came up doing the game controller versions is the future need to separate individual rates out so that pitch/roll/yaw all have their own - that would go hand-in-hand with the idea of letting the user decide if all their rates are then linked, or just roll/pitch, or would nominate one to use when they are manually altering rates.

But I also don't want huge amounts of text here, so some more thought is needed.  It might be useful to have some throttle expo available though - again, the effects of a high powered quad in LOS mode makes it difficult to hold a very stable hover, so throttle expo might help.
