### ISSUE TITLE
Transmitter deadzone configuration / disable option

### ISSUE THREAD

**Issue by fxbisto** [CurryKitten/CurryKitten-Sim#47]
Hi Wayne

Fantastic job developing this, nothing but love so far bar one thing (as per this issue title)
My usual rates are fairly high in terms of the centre stick response - RCrate=1.4; Srate=0.4;expo=0.1
There is too much dead-zone to effectively use these rates...is that something you've added in which would be easy to disable or is this a Unity limitation?
I normally use Velocidrone and DRL, both of which have the option to disable deadzone completely, so I'm fairly confident this is not an issue with my particular hardware. It makes for much finer and smoother control.

I use a Flysky i6 for simulators. It's connected to the computer via an iA6B Rx hooked up to an old F4 flight controller with the betaflight option USB_HID_CDC enabled. For anybody unfamiliar with this option it enables betaflight to create a joystick output so you can simulate wireless. The issue is identical on both my Windows and Linux machines.

Just as a side-note I also find the handling and throttle feel much more in-line with all my 5" craft by setting throttle multiplier to 0.45 & gravity to 1.50.

Thanks once again for the great work! :)
All the best

**Comment by CurryKitten** [comment]
Interesting question - I had to move away from Unity's own input system as it wouldn't allow me to calibrate a control at all, leaving a lot of radios not working.  I'm using the 3rd part native plugin ReWired, which (aside form support calibration and controller remapping) does *something* with deadzones.  So I'll investigate - if there's an option to simply turn on/off I'll add that.  It's a very over-engineered API though, so off's on it won't quite be that easy

**Comment by CurryKitten** [comment]
Ok, checked this out - because the controllers we all use (i.e not a regular joystick) are "unknown" they are given an arbitrary figure of 0.1 for the deadzone.  This may be applicable in some controllers, but not others.  I noticed the 360 controller gets a deadzone of 0.25 but still drifts for me sometimes.

I think the solution is to add a slider for the deadzone, so you can see what value it starts on, and then move it to zero (off) if you like, or if the quad drifts around at all without input, then increase it.  I'm not sure what that top end figure should be - but I'll mess around and find that

**Comment by CurryKitten** [comment]
Done.  I decided to translate the raw figures into a percentage figure so people have more of a concept of what it means, and make sure it reads the default deadzone on each type of stick if none has been defined.  The adjustment goes up to 50%, but you got to hope that that sort of value isn't needed.  Any change that's made is saved in the game data so that chosen setting will persist.

![Screenshot 2020-04-26 at 14 31 35](https://user-images.githubusercontent.com/12443664/80309158-0af28c00-87cb-11ea-8818-bbd1cdec1be0.jpg)


I tested with 0% on a radio, and the control certainly seemed tight.  @fxbisto If you want a build to test on send me over an email at currykittensim@gmail.com (and let me know what platform you are running on - I assumed Windows 64)

**Comment by CurryKitten** [comment]
Heard back from @fxbisto to say he'd tested the code and it was working.  He was recommending a smaller range of adjustment so he could have much finer control.  I'm not going to do this as a regular gamepad control already starts with a 25% deadzone and sometimes still isn't great !  Each percentage point isn't a pure jump though, although we are rounding to percentages in the display, in the code it's a pure float between 0 and 0.5.
