### ISSUE TITLE
Xbox 360 Controller - Calibration fails, and stick no longer work

### ISSUE THREAD

**Issue by danielchan9999** [CurryKitten/CurryKitten-Sim#49]
Hey,

Firstly - great app.

**Environment:**
MacOS Mojave, MacBook Pro i7, 16gb Ram
Controller - 360 Gamepad - using the Xbox 360 Controllers Driver.
CK-FPV-Sim-Mac-046b [latest beta release]

**Issue:**
Stick movement is not detected by the sim. It does detect that the 360 controller is connected (and recognises when unplugged)
 - It was working initially, but I realised I had to switch to gamepad mode to get the throttled zeroed to the centre position. I moved to the Radio / Joystick Setup. Now I think I clicked Calibrate Sticks, and nothing happened. I then switched Stick Type to gamepad and saw the blue dot for throttle moved to the bottom position for throttle. 
 - after this, stick input does nothing.
 - controller buttons still work (ie Y, B, A, X and triggers) I can see them working in the Show Radio Debug
 - when trying to use REMAP CONTROLS, it shows "no stick detected"
 - The sticks just don't work.

**Troubleshooting**
 - checked the mac driver. It shows the controller working, I can move the sticks and see it respond
 - the controller works fine for FreeRider FPV which I also have installed on this mac.
 - the same issue occurs on 045a version.
 - restarted mac, no change
 - re-downloaded a new version of app, no change

Is there any config file for this sim written in Mac that is persisting a config that breaks this? It did work initially, and then I can never get it to work again after pressing either Calibrate or Stick Type.

The app looks great, and kudos for getting it this far. If this can be solved it would be awesome.

**Comment by danielchan9999** [comment]
Update: Xbox One USB controller seems to work. I haven't tried calibrate or remap controls. But I can fly with it. I can't explain why the 360 controller has failed.

**Comment by CurryKitten** [comment]
The good news is that a wired 360 controller definitely works - but just replicating your "click on calibrate" comment, something does go wieird and it loses it's calibration data - so I'll fix this.

In the meantime though, you can use this as a workaround.  If you run the sim, unplug the 360 controller, and reset the sim to defaults using the setup menu, and then exit the sim.  Start it back up and plug in the 360 controller and it should now work as it did.  It's a known pre-configured controller, so doesn't need to be calibrated - but obviously something is going adrift here

**Comment by danielchan9999** [comment]
Awesome. The workaround worked. Thanks so much.

**Comment by CurryKitten** [comment]
Ok, weird.  For some reason in my calibration code I say that if the number of axis in a controller is less than 8, then make it 8 - otherwise use the actual number of axis a controller has.

This - as you might expect - falls over in a heap when you are iterating through the number of axis to get calibration data from the objects as the objects don't exist when you go past the actual number of axis.  Helpfully, I can't remember why I wrote this, but it could never work like this so I'm confident actually just checking the number of axis that a controller has (in the Xbox 360's case the answer is 6) and using that answer to iterate through.

I made the change and it fixes the 360 issue - so that'll go into the next release.
