### ISSUE TITLE
munmap_chunk(): invalid pointer on Linux

### ISSUE THREAD

**Issue by OMGChase** [CurryKitten/CurryKitten-Sim#70]
Hello.

Launching the sim on Linux and getting the error:

`munmap_chunk(): invalid pointer`
`Aborted (core dumped)`

Could be something I'm doing wrong, as I'm quite new to Linux, but steps to reproduce are:

1.open terminal in directory
2.`chmod +x CK-FPV-Sim-Linux64-050b.x86_64`
3.`./CK-FPV-Sim-Linux64-050b.x86_64`

Running Ubuntu 20.04 focal (x86-64) with Cinnamon DE (4.4.8)

**Comment by CurryKitten** [comment]
Whoops, sorry @OMGChase - was not paying attention and didn't see this one come in.  Are you running on an AMD GPU - from what I can tell it's a driver issue here, specifically (I think) the AMDGPU Pro driver.  I see a reference to it being fixed in 20.40.  I'm not entirely sure what package name we're talking about here, but can you check what (if any) versions of *amdgpu* you have installed

**Comment by OMGChase** [comment]
Running the game on Mesa drivers now without an issue.

Closing the issue.
